;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-delete-forward
	c-electric-pound
	c-electric-star
	comint-delchar-or-maybe-eof
	dabbrev-expand
	js-insert-and-indent
	ns-copy-including-secondary
	org-beginning-of-line
	org-cycle
	org-delete-char
	org-end-of-line
	org-force-self-insert
	org-kill-line
	org-self-insert-command
	perl-electric-terminator
	perl-indent-command
	yas/expand
	))

(setq mc/cmds-to-run-once
      '(
	abort-recursive-edit
	beginning-of-buffer
	comint-previous-input
	dired-unmark-all-files
	end-of-buffer
	kill-region
	kmacro-start-macro-or-insert-counter
	org-shiftright
	python-backspace
	ruby-electric-brace
	split-window-horizontally
	split-window-vertically
	))
